### ISSUE TITLE
Did you filter out test sets from Downstream Benchmarks?

### ISSUE THREAD

**Issue by JoelNiklaus** [Breakend/PileOfLaw#14]
Hi,

Great dataset! Thank you very much for curating it!
I was wondering, if you filtered out the test sets of downstream benchmarks like LexGLUE or BillSum?

Cheers,
Joel

**Comment by Breakend** [comment]
Hi, 

The released version of the data on HF does not filter for downstream test sets (partly because the main goal of the paper is to focus on data filtering standards rather than being benchmarked against these particular downstream tasks). Thanks for your interest!

**Comment by JoelNiklaus** [comment]
Thank you very much for the quick reply!
